library groupvan;

// Main SDK Interface - Only singleton pattern allowed
export 'src/client.dart'
    show
        GroupVAN,
        GroupVanDefaults,
        GroupVANClient,
        GroupVANAuth,
        GroupVANVehicles,
        GroupVANCatalogs,
        GroupVANSearch,
        GroupVANCatman,
        AuthUser,
        AuthSession,
        AuthChangeEvent,
        AuthState;

// Token storage (for custom implementations)
export 'src/auth/auth_manager.dart'
    show TokenStorage, SecureTokenStorage, MemoryTokenStorage, WebTokenStorage;

// Session management

// Essential types and exceptions for error handling
export 'src/core/exceptions.dart';
export 'src/core/response.dart' show Result;

// Public models that developers need
export 'src/models/models.dart'
    show
        Vehicle,
        VehicleGroup,
        VehicleCategory,
        Catalog,
        CatalogType,
        SupplyCategory,
        SupplySubcategory,
        TopCategory,
        ApplicationAsset,
        ApplicationAssetsRequest,
        DisplayTier,
        PartType,
        PartTypeRequest,
        ProductListingRequest,
        ProductListing,
        Part,
        PartApplication,
        PartApplicationDisplay,
        Brand,
        Attribute,
        AttributeFamily,
        VehicleFilterRequest,
        VehicleFilterResponse,
        VehicleFilterOption,
        Fleet,
        EngineSearchRequest,
        VinSearchRequest,
        PlateSearchRequest,
        User,
        CartBehavior,
        Location,
        Asset,
        SpinAsset,
        SpinAssetResponse,
        ItemPricing,
        ItemPricingLocation,
        Product,
        ProductPricingRequest,
        Interchange,
        InterchangeBrand,
        InterchangePartType,
        InterchangePart,
        ProductInfoResponse,
        InfoAttribute,
        Document,
        OmniSearchResponse,
        VehicleAndPartType,
        MemberCategory,
        SuggestionsResponse,
        AddToCartRequest,
        RemoveFromCartRequest,
        CartResponse,
        CartItem,
        CartItemType,
        RemovalItem,
        LocationDetails,
        BuyersGuideRequest,
        BuyersGuideResponse,
        BuyersGuideViewType,
        BuyersGuideGroup,
        BuyersGuideMake,
        BuyersGuideModel,
        BuyersGuideYear,
        BuyersGuideVehicle,
        BuyersGuidePartTerm,
        FlatBuyersGuideRequest,
        FlatBuyersGuideResponse,
        FlatBuyersGuideItem,
        InvoiceRequest,
        InvoiceResponse,
        Invoice,
        InvoiceDetail,
        StatementRequest,
        StatementResponse,
        Statement,
        StatementDetail,
        CheckoutRequest,
        CheckoutResponse,
        Ad,
        Campaign,
        AdUpdate,
        CampaignCreate,
        CampaignUpdate,
        CustomCatalog,
        CatalogCreateRequest,
        CatalogUpdateRequest,
        CatalogImportRow,
        CatalogImportRequest,
        CatalogImportResult,
        CommodityCategory,
        CommoditySubCategory,
        CommodityPart,
        CatalogData,
        UserType;

// Constants
export 'src/constants.dart' show CountryCode, CountryDivisionCode;
